# Generated by Django 4.2.1 on 2023-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bloodGroup',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='standard',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
