# Generated by Django 4.2.1 on 2023-06-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='standard',
        ),
    ]
