# Generated by Django 4.2.1 on 2023-06-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_mother_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='is_used',
        ),
    ]
